[package]
name = "toner"
version = "0.2.11"
edition.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true
categories.workspace = true
description = "SDK for TON blockchain"

[dependencies]
